[package]
name = "cdn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
reqwest = "0.12.7"
semver = "1.0.23"
serde = { version= "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0",  features = ["macros", "rt-multi-thread"] }
